-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBjiZ6wYk+9huXGdV
OiituIAmGw/HP3GpEujkXyZbNC6gCgYIKoZIzj0DAQehRANCAATcCPlCmsrPYAQu
HEqdoA82Z9xQJnY6TrtrP5FsaYxG+kpdGWYAXkW878cyidF6frRmZfQJwVHwmZJf
zcUz0DlI
-----END PRIVATE KEY-----