# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FanConnectNow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FanConnectNow
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SwiftyPickerPopover'

end

target 'PhotoTextingLine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoTextingLine
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SwiftyPickerPopover'

end

target 'SMSFactory' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMSFactory
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SwiftyPickerPopover'

end

target 'TextingLine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextingLine
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SwiftyPickerPopover'

  end
  
  target 'Text_Attendant' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for Text_Attendant
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'SwiftyPickerPopover'

end
