# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FanConnectNow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FanConnectNow

end

target 'PhotoTextingLine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoTextingLine

end

target 'SMSFactory' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMSFactory

end

target 'TextingLine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextingLine
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
end
