-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghdi5BQE1DVgjaL3n
uF3VLwKna2xFR+V8hMuJfrzJHTygCgYIKoZIzj0DAQehRANCAARBV/CK8XdEIczD
8o8tBnSURMA47oCsYezQou/jR/GDvu/40rIhDVviWAo/iXJwm39CWAL8awahlkHv
OSPFy9cS
-----END PRIVATE KEY-----